---
- name: restart nginx
  systemd:
    name: nginx
    state: reloaded
  become: true
  become_user: root

- name: stop nginx
  systemd:
    name: nginx
    state: stopped
  become: true
  become_user: root

- name: start nginx
  systemd:
    name: nginx
    state: started
  become: true
  become_user: root