---
- name: update repositories
  apt:
   update_cache: yes
  become: true
  become_user: root

- name: Update all packages to the latest version
  apt:
    upgrade: dist
  become: true
  become_user: root