---
- name: install nginx and dependencies
  apt:
    name: ['nginx', 'python3-pip', 'python-pip', 'nginx', 'letsencrypt', 'git', 'virtualenv', 'python3-venv', 'gcc', 'python3-certbot-nginx']
    state: present
  become: true
  become_user: root

- name: configure default site for nginx
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
    mode: 0640
  become: true
  become_user: root
  notify: stop nginx

- name: check cert dir exists
  stat: 
    path: /etc/letsencrypt/live/{{ default_url }}
  register: p
  become: true
  become_user: root

- name: stop nginx
  systemd:
    name: nginx
    state: stopped
  become: true
  become_user: root

- name: create certificate
  command: "certbot --nginx --agree-tos --standalone --email {{ default_email }} --non-interactive  -d {{ default_url }}"
  become: true
  become_user: root
  when: p.stat.isdir is not defined 
  notify: start nginx

- name: configure pysshauthz site redirect for nginx
  template:
    src: pysshauthz.j2
    dest: /etc/nginx/snippets/pysshauthz.conf
    mode: 0640
  become: true
  become_user: root
  notify: start nginx
